import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1772190361842 implements MigrationInterface {
    name = 'InitialSchema1772190361842'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "contributions" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "missionId" varchar NOT NULL, "type" varchar NOT NULL, "message" text, "status" varchar NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_3756ee3b48056ae019b68d5acdb" UNIQUE ("userId", "missionId", "type"))`);
        await queryRunner.query(`CREATE TABLE "offers" ("id" varchar PRIMARY KEY NOT NULL, "creatorId" varchar NOT NULL, "title" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar NOT NULL, "offerType" varchar NOT NULL, "visibility" varchar NOT NULL DEFAULT ('public'), "locationLat" float, "locationLng" float, "locationRadiusKm" integer NOT NULL DEFAULT (10), "status" varchar NOT NULL DEFAULT ('ouverte'), "tags" text NOT NULL, "availability" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "expiresAt" datetime NOT NULL, "closedAt" datetime)`);
        await queryRunner.query(`CREATE TABLE "correlations" ("id" varchar PRIMARY KEY NOT NULL, "missionId" varchar NOT NULL, "offerId" varchar NOT NULL, "score" float NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c2cf81415aa98b55d598221f6dd" UNIQUE ("missionId", "offerId"))`);
        await queryRunner.query(`CREATE TABLE "missions" ("id" varchar PRIMARY KEY NOT NULL, "creatorId" varchar NOT NULL, "title" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar NOT NULL, "helpType" varchar NOT NULL, "urgency" varchar NOT NULL, "visibility" varchar NOT NULL DEFAULT ('public'), "locationLat" float, "locationLng" float, "locationRadiusKm" integer NOT NULL DEFAULT (10), "status" varchar NOT NULL DEFAULT ('ouverte'), "progressPercent" integer NOT NULL DEFAULT (0), "tags" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "expiresAt" datetime NOT NULL, "closedAt" datetime, "closureFeedback" text, "closureThanks" text)`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "type" varchar NOT NULL, "title" varchar(200) NOT NULL, "body" text, "referenceType" varchar, "referenceId" varchar, "isRead" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "email" varchar(255) NOT NULL, "passwordHash" varchar(255), "oauthProvider" varchar(50), "oauthProviderId" varchar(255), "displayName" varchar(100) NOT NULL, "avatarUrl" text, "locationLat" float, "locationLng" float, "isPremium" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "temporary_contributions" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "missionId" varchar NOT NULL, "type" varchar NOT NULL, "message" text, "status" varchar NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_3756ee3b48056ae019b68d5acdb" UNIQUE ("userId", "missionId", "type"), CONSTRAINT "FK_55141bcc2980d26a4870712f3f4" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_43a6e5d0fa1ed23b85d61359728" FOREIGN KEY ("missionId") REFERENCES "missions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_contributions"("id", "userId", "missionId", "type", "message", "status", "createdAt") SELECT "id", "userId", "missionId", "type", "message", "status", "createdAt" FROM "contributions"`);
        await queryRunner.query(`DROP TABLE "contributions"`);
        await queryRunner.query(`ALTER TABLE "temporary_contributions" RENAME TO "contributions"`);
        await queryRunner.query(`CREATE TABLE "temporary_offers" ("id" varchar PRIMARY KEY NOT NULL, "creatorId" varchar NOT NULL, "title" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar NOT NULL, "offerType" varchar NOT NULL, "visibility" varchar NOT NULL DEFAULT ('public'), "locationLat" float, "locationLng" float, "locationRadiusKm" integer NOT NULL DEFAULT (10), "status" varchar NOT NULL DEFAULT ('ouverte'), "tags" text NOT NULL, "availability" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "expiresAt" datetime NOT NULL, "closedAt" datetime, CONSTRAINT "FK_508ec375c35238e1479d1486ac9" FOREIGN KEY ("creatorId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_offers"("id", "creatorId", "title", "description", "category", "offerType", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "tags", "availability", "createdAt", "expiresAt", "closedAt") SELECT "id", "creatorId", "title", "description", "category", "offerType", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "tags", "availability", "createdAt", "expiresAt", "closedAt" FROM "offers"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`ALTER TABLE "temporary_offers" RENAME TO "offers"`);
        await queryRunner.query(`CREATE TABLE "temporary_correlations" ("id" varchar PRIMARY KEY NOT NULL, "missionId" varchar NOT NULL, "offerId" varchar NOT NULL, "score" float NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c2cf81415aa98b55d598221f6dd" UNIQUE ("missionId", "offerId"), CONSTRAINT "FK_6b2901d22c60358306633317c16" FOREIGN KEY ("missionId") REFERENCES "missions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_cf39b59cf49bec6cc8512aa53ef" FOREIGN KEY ("offerId") REFERENCES "offers" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_correlations"("id", "missionId", "offerId", "score", "createdAt") SELECT "id", "missionId", "offerId", "score", "createdAt" FROM "correlations"`);
        await queryRunner.query(`DROP TABLE "correlations"`);
        await queryRunner.query(`ALTER TABLE "temporary_correlations" RENAME TO "correlations"`);
        await queryRunner.query(`CREATE TABLE "temporary_missions" ("id" varchar PRIMARY KEY NOT NULL, "creatorId" varchar NOT NULL, "title" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar NOT NULL, "helpType" varchar NOT NULL, "urgency" varchar NOT NULL, "visibility" varchar NOT NULL DEFAULT ('public'), "locationLat" float, "locationLng" float, "locationRadiusKm" integer NOT NULL DEFAULT (10), "status" varchar NOT NULL DEFAULT ('ouverte'), "progressPercent" integer NOT NULL DEFAULT (0), "tags" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "expiresAt" datetime NOT NULL, "closedAt" datetime, "closureFeedback" text, "closureThanks" text, CONSTRAINT "FK_5602133093ca6fdcb9ca7c670a5" FOREIGN KEY ("creatorId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_missions"("id", "creatorId", "title", "description", "category", "helpType", "urgency", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "progressPercent", "tags", "createdAt", "expiresAt", "closedAt", "closureFeedback", "closureThanks") SELECT "id", "creatorId", "title", "description", "category", "helpType", "urgency", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "progressPercent", "tags", "createdAt", "expiresAt", "closedAt", "closureFeedback", "closureThanks" FROM "missions"`);
        await queryRunner.query(`DROP TABLE "missions"`);
        await queryRunner.query(`ALTER TABLE "temporary_missions" RENAME TO "missions"`);
        await queryRunner.query(`CREATE TABLE "temporary_notifications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "type" varchar NOT NULL, "title" varchar(200) NOT NULL, "body" text, "referenceType" varchar, "referenceId" varchar, "isRead" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_notifications"("id", "userId", "type", "title", "body", "referenceType", "referenceId", "isRead", "createdAt") SELECT "id", "userId", "type", "title", "body", "referenceType", "referenceId", "isRead", "createdAt" FROM "notifications"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`ALTER TABLE "temporary_notifications" RENAME TO "notifications"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" RENAME TO "temporary_notifications"`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "type" varchar NOT NULL, "title" varchar(200) NOT NULL, "body" text, "referenceType" varchar, "referenceId" varchar, "isRead" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "notifications"("id", "userId", "type", "title", "body", "referenceType", "referenceId", "isRead", "createdAt") SELECT "id", "userId", "type", "title", "body", "referenceType", "referenceId", "isRead", "createdAt" FROM "temporary_notifications"`);
        await queryRunner.query(`DROP TABLE "temporary_notifications"`);
        await queryRunner.query(`ALTER TABLE "missions" RENAME TO "temporary_missions"`);
        await queryRunner.query(`CREATE TABLE "missions" ("id" varchar PRIMARY KEY NOT NULL, "creatorId" varchar NOT NULL, "title" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar NOT NULL, "helpType" varchar NOT NULL, "urgency" varchar NOT NULL, "visibility" varchar NOT NULL DEFAULT ('public'), "locationLat" float, "locationLng" float, "locationRadiusKm" integer NOT NULL DEFAULT (10), "status" varchar NOT NULL DEFAULT ('ouverte'), "progressPercent" integer NOT NULL DEFAULT (0), "tags" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "expiresAt" datetime NOT NULL, "closedAt" datetime, "closureFeedback" text, "closureThanks" text)`);
        await queryRunner.query(`INSERT INTO "missions"("id", "creatorId", "title", "description", "category", "helpType", "urgency", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "progressPercent", "tags", "createdAt", "expiresAt", "closedAt", "closureFeedback", "closureThanks") SELECT "id", "creatorId", "title", "description", "category", "helpType", "urgency", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "progressPercent", "tags", "createdAt", "expiresAt", "closedAt", "closureFeedback", "closureThanks" FROM "temporary_missions"`);
        await queryRunner.query(`DROP TABLE "temporary_missions"`);
        await queryRunner.query(`ALTER TABLE "correlations" RENAME TO "temporary_correlations"`);
        await queryRunner.query(`CREATE TABLE "correlations" ("id" varchar PRIMARY KEY NOT NULL, "missionId" varchar NOT NULL, "offerId" varchar NOT NULL, "score" float NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c2cf81415aa98b55d598221f6dd" UNIQUE ("missionId", "offerId"))`);
        await queryRunner.query(`INSERT INTO "correlations"("id", "missionId", "offerId", "score", "createdAt") SELECT "id", "missionId", "offerId", "score", "createdAt" FROM "temporary_correlations"`);
        await queryRunner.query(`DROP TABLE "temporary_correlations"`);
        await queryRunner.query(`ALTER TABLE "offers" RENAME TO "temporary_offers"`);
        await queryRunner.query(`CREATE TABLE "offers" ("id" varchar PRIMARY KEY NOT NULL, "creatorId" varchar NOT NULL, "title" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar NOT NULL, "offerType" varchar NOT NULL, "visibility" varchar NOT NULL DEFAULT ('public'), "locationLat" float, "locationLng" float, "locationRadiusKm" integer NOT NULL DEFAULT (10), "status" varchar NOT NULL DEFAULT ('ouverte'), "tags" text NOT NULL, "availability" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "expiresAt" datetime NOT NULL, "closedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "offers"("id", "creatorId", "title", "description", "category", "offerType", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "tags", "availability", "createdAt", "expiresAt", "closedAt") SELECT "id", "creatorId", "title", "description", "category", "offerType", "visibility", "locationLat", "locationLng", "locationRadiusKm", "status", "tags", "availability", "createdAt", "expiresAt", "closedAt" FROM "temporary_offers"`);
        await queryRunner.query(`DROP TABLE "temporary_offers"`);
        await queryRunner.query(`ALTER TABLE "contributions" RENAME TO "temporary_contributions"`);
        await queryRunner.query(`CREATE TABLE "contributions" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "missionId" varchar NOT NULL, "type" varchar NOT NULL, "message" text, "status" varchar NOT NULL DEFAULT ('active'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_3756ee3b48056ae019b68d5acdb" UNIQUE ("userId", "missionId", "type"))`);
        await queryRunner.query(`INSERT INTO "contributions"("id", "userId", "missionId", "type", "message", "status", "createdAt") SELECT "id", "userId", "missionId", "type", "message", "status", "createdAt" FROM "temporary_contributions"`);
        await queryRunner.query(`DROP TABLE "temporary_contributions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "missions"`);
        await queryRunner.query(`DROP TABLE "correlations"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`DROP TABLE "contributions"`);
    }

}
